name: PR checks

on:
  pull_request:
    branches:
      - master

jobs:
  pr_checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install

    - name: Run Typescript
      run: yarn tsc

    - name: Run unit tests
      run: yarn test